config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'application#home'

  # resources :users, only: [:new, :create, :show, :index]

  # resources :concerts do
  #   resources :attendees, only: [:create]
  #   resources :tickets, only: [:create]
  #   resources :pieces
  # end
  #
  # resources :attendees, only: [:show, :index, :edit, :update]

  resources :users, only: [:new, :create]

  resources :concerts, only: [:new, :create, :show, :index]

  resources :sessions, only: [:create]

  post '/logout', to: 'sessions#destroy'

  get '/auth/github/callback' => 'sessions#create_via_omniauth'

end

app/models/piece.rb
class Piece < ActiveRecord::Base
  belongs_to :concert

  validates :title, :composer, presence: true
  validates :date_composed, numericality: { greater_than: 0 }
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  def new
    @piece = Piece.new
    @concert = Concert.find_by(id: params[:concert_id])
  end

  def create
    @concert = Concert.find(params[:concert_id])
    @piece = Piece.new(piece_params)
    @concert.pieces << @piece

    if @concert.save
      redirect_to concert_pieces_path(@concert)
    else
      render :new
    end
  end

  def edit
    @piece = Piece.find_by(id: params[:id])
  end

  def update
    @piece = Piece.find_by(id: params[:id])
    @piece.update(piece_params)
    @concert = Concert.find_by(id: params[:concert_id])

    if @piece.save
      redirect_to concert_piece_path(@piece.concert, @piece)
    else
      render :edit
    end
  end

  def show
    @piece = Piece.find_by(id: params[:id])
  end

  def index
    @concert = Concert.find_by(id: params[:concert_id])
    @pieces = @concert.pieces
  end

  def destroy
    Piece.find_by(id: params[:id]).destroy
    concert = Concert.find_by(id: params[:concert_id])
    redirect_to concert_pieces_path(concert)
  end

  private

  def piece_params
    params.require(:piece).permit(:title, :composer, :date_composed)
  end
end

app/views/pieces/_form.html.erb
<%= form_for [@concert, @piece] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br><br>
  <%= f.label :composer %>
  <%= f.text_field :composer %><br><br>
  <%= f.label :date_composed %>
  <%= f.number_field :date_composed %><br><br>
  <%= f.submit %>
<% end %>

app/views/pieces/edit.html.erb
<%= render partial: "application/errors", locals: {object: @piece} %>

<%= render "form" %>

app/views/pieces/index.html.erb
<h3><%= @concert.title %></h3>

<h4>Program:</h4>

<ul>
  <% @pieces.each do |piece| %>
    <li><strong><%= piece.composer %></strong> <%= link_to "#{piece.title} #{piece.date_composed}", concert_piece_path(@concert, piece) %></li>
  <% end %>
</ul>

<%= link_to "Add a new piece to this concert", new_concert_piece_path(@concert) %>

app/views/pieces/new.html.erb
<h3>Add a new piece to <%= @concert.title %></h3>

<%= render partial: "application/errors", locals: {object: @piece} %>

<%= render "form" %>

app/views/pieces/show.html.erb
<h3>Title: <%= @piece.title %></h3>

<h3>Composer: <%= @piece.composer %></h3>

<h3>Date Composed: <%= @piece.date_composed %></h3>

<h4>This piece will be performed at: <%= link_to @piece.concert.title, concert_path(@piece.concert) %></h4>

<%= link_to "Edit this piece", edit_concert_piece_path(@piece.concert, @piece) %><br><br>

<%= link_to "Delete this piece", concert_piece_path(@piece.concert, @piece), method: :delete %>