config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'application#home'

  # resources :users, only: [:new, :create, :show, :index]

  # resources :concerts do
  #   resources :attendees, only: [:create]
  #   resources :tickets, only: [:create]
  #   resources :pieces
  # end
  #
  # resources :attendees, only: [:show, :index, :edit, :update]

  resources :users, only: [:new, :create]

  resources :concerts, only: [:new, :create, :show, :index]

  resources :sessions, only: [:create]

  post '/logout', to: 'sessions#destroy'

  get '/auth/github/callback' => 'sessions#create_via_omniauth'

end

app/models/concert.rb
class Concert < ActiveRecord::Base
  has_many :tickets
  has_many :attendees, through: :tickets
  has_many :pieces

  validates :title, :venue, :date, presence: true
  validates :title, uniqueness: true
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def new
    @concert = Concert.new
    render "concerts/new", layout: false
  end

  def create
    @concert = Concert.create(concert_params)
    render json: @concert
  end

  def index
    @concerts = Concert.all
    render json: @concerts
  end

  def edit
    @concert = Concert.find(params[:id])
  end

  def show
    @concert = Concert.find(params[:id])
    render json: @concert, serializer: AttendeeConcertSerializer
  end

  def update
    @concert = Concert.find(params[:id])
    @concert.update(concert_params)

    if @concert.save
      redirect_to concert_path(@concert)
    else
      render :edit
    end
  end

  private

  def concert_params
    params.require(:concert).permit(:title, :venue, :date)
  end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
  def display_date(concert)
    DateTime.parse(concert.date).to_date.strftime("%A, %B %e, %Y")
  end
end

app/views/concerts/_add_attendee.html.erb
<h3>Select an existing attendee to add to concert:</h3>

<%= form_tag(concert_tickets_path(@concert)) do %>
  <%= collection_select(:ticket, :attendee_id, Attendee.all, :id, :full_name) %>
  <%= label_tag "ticket[seat_number]", "Seat Number:" %>
  <%= number_field_tag "ticket[seat_number]" %>
  <%= hidden_field_tag "ticket[concert_id]", @concert.id %>
  <%= submit_tag "Add to concert" %>
<% end %>

<h3>Create a new attendee to add to concert:</h3>

<%= form_tag concert_attendees_path(@concert) do %>
  <%= label_tag "attendee[first_name]", "First Name:" %>
  <%= text_field_tag "attendee[first_name]" %><br><br>
  <%= label_tag "attendee[last_name]", "Last Name:" %>
  <%= text_field_tag "attendee[last_name]" %><br><br>
  <%= label_tag "ticket[seat_number]", "Seat Number:" %>
  <%= number_field_tag "ticket[seat_number]" %><br><br>
  <%= submit_tag "Add Attendee" %>
<% end %>

app/views/concerts/_form.html.erb
<%= form_for @concert do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br><br>
  <%= f.label :venue %>
  <%= f.text_field :venue %><br><br>
  <%= f.label :date %>
  <%= f.date_field :date %><br><br>
  <%= f.submit %>
<% end %>

app/views/concerts/edit.html.erb
<h2>Edit Concert:</h2>

<%= render partial: "application/errors", locals: {object: @concert} %>

<%= render "form" %><br>

app/views/concerts/index.html.erb
<h2>All Concerts:</h2>

<ul>
  <% @concerts.each do |concert| %>
    <li><%= display_date(concert) %> - <%= link_to concert.title, concert_path(concert) %></li>
  <% end %>
</ul>

<%= link_to "Create a Concert", new_concert_path %>

app/views/concerts/new.html.erb
<h2>Create a new Concert:</h2>

<%= render partial: "application/errors", locals: {object: @concert} %>

<%= render "form" %><br>

app/views/concerts/show.html.erb
<h2>Title: <%= @concert.title %></h2>

<h3>Date: <%= display_date(@concert) %></h3>

<h3>Venue: <%= @concert.venue %></h3>

<h3><%= link_to "Program", concert_pieces_path(@concert) %></h3>

<%= link_to "Edit Concert Details", edit_concert_path(@concert) %><br>

<h3>Attendees:</h3>

<% if @concert.attendees.empty? %>
  <ul>
    <li>None</li>
  </ul>
<% else %>
  <%= render "attendees/table" %><br>
<% end %>

<%= render "add_attendee" %>